// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
)

type Todo struct {
	ID          int32
	Title       string
	Description sql.NullString
	DueDate     sql.NullTime
	Completed   sql.NullBool
}
